# ──────────────────────────────────────────────────────────
# Secrets — Backend environment variables (Trendz)
# ──────────────────────────────────────────────────────────
apiVersion: v1
kind: Secret
metadata:
  name: trendz-backend-secrets
  namespace: trendz
  labels:
    app: trendz
    component: backend
type: Opaque
data:
  JWT_SECRET: VHJlbmRaU21n
  ADMIN_EMAIL: YWRtaW5AZXhhbXBsZS5jb20=
  ADMIN_PASSWORD: MzIx
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9jaGV0dWMwNDA0X2RiX3VzZXI6dnNhNUZmbm1mbm95SzFzdUBjbHVzdGVyMC5xMHFhcW9rLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
  CLOUDINARY_API_KEY: NDgxMjU5Mzk4Njk2MzE3
  CLOUDINARY_SECRET_KEY: WU03QlpaVzFONDNldVZkSDNvUUxkZE5rUVFB
  CLOUDINARY_NAME: ZHBsMDV0bHFv
